### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by dehnert** [tech-squares/squaresdb#10]
We'll need to have the DB actually run somewhere. Ideally, I'd run it on scripts, which I know well, is free, and MIT students are well equipped to deal with.

However, scripts' newer, non default pool has F30, which has been out of support for a while. Also, I believe I'm now depending on Django 3.2 LTS (which I think is basically the right choice, except for possibly 2.2 LTS). Even if scripts updated fedora, the latest released is [F34](https://en.m.wikipedia.org/wiki/Fedora_(operating_system)), which [appears to have](https://src.fedoraproject.org/rpms/python-django) 3.1. virtualenvs are an option, but using system packages appears to prohibit newer Django, not using system packages is hard due to the lack of xmlsec pypi binaries or headers on scripts, plus it's very slow.

I'm thinking a cloud deployment is the way to go - maybe Google app engine? https://cloud.google.com/python/django/appengine is likely informative on this front.

**Comment by dehnert** [comment]
It may be reasonable to make GitHub actions deploy to GAE: https://github.com/google-github-actions/deploy-appengine

**Comment by dehnert** [comment]
(note also that GAE has an always free tier that I bet works)

**Comment by dehnert** [comment]
.... Apparently GCP always free doesn't really have a SQL DB option - Cloud SQL isn't in always free and is kinda expensive

**Comment by dehnert** [comment]
Azure appears to have free VMs and database for the first year. https://azure.microsoft.com/en-us/free/

Amazon appears to have free VM and database for the first year. https://aws.amazon.com/free/

Oracle has always free VMs and database (https://www.oracle.com/cloud/free/#always-free)

Google has an always free VM, but we might already be using it for photos

**Comment by kchen** [comment]
We're using the always free VM for photos, but it could be used for other things as well. The VM runs a local MySQL database, which is backed up to local disk, and the disk is periodically snapshotted.

**Comment by kchen** [comment]
Correction: We're using a paid VM, because the free VM is too slow for photo purposes.

**Comment by dehnert** [comment]
It is now running on the photos VM.
